apiVersion: apps/v1
kind: Deployment
metadata:
  name: ekart-deployment
  labels:
    app: ekart

spec:
  replicas: 1

  selector:
    matchLabels:
      app: ekart

  template:
    metadata:
      labels:
        app: ekart

    spec:
      imagePullSecrets:
      - name: dockerhub-secret
      
      containers:
      - name: ekart-container
        image: yashwantlohar/ekart:latest
        imagePullPolicy: Always

        ports:
        - containerPort: 8070
          hostPort: 8070

---
apiVersion: v1
kind: Service
metadata:
  name: ekart-service

spec:
  selector:
    app: ekart

  ports:
    - protocol: TCP
      port: 8070
      targetPort: 8070

  type: NodePort
